const questionsJson = () => [
  {
    question: 'What is the name for the Jewish New Year?',
    correct_answer: 'Rosh Hashanah',
    incorrect_answers: ['Hanukkah', 'Yom Kippur', 'Kwanza'],
  },
  {
    question: 'How many blue stripes are there on the U.S. flag?',
    correct_answer: '0',
    incorrect_answers: ['6', '7', '13'],
  },
  {
    question: 'Which one of these characters is not friends with Harry Potter?',
    correct_answer: 'Draco Malfoy',
    incorrect_answers: [
      'Ron Weasley',
      'Neville Longbottom',
      'Hermione Granger',
    ],
  },
  {
    question: 'What is the color of Donald Duck’s bowtie?',
    correct_answer: 'Red',
    incorrect_answers: ['Yellow', 'Blue', 'White'],
  },
  {
    question: 'What was the name of the band Lionel Richie was a part of?',
    correct_answer: 'Commodores',
    incorrect_answers: [
      'King Harvest',
      'Spectrums',
      'The Marshall Tucker Band',
    ],
  },
  {
    question: 'Which animal does not appear in the Chinese zodiac?',
    correct_answer: 'Hummingbird',
    incorrect_answers: ['Dragon', 'Rabbit', 'Dog'],
  },
  {
    question: 'Which country held the 2016 Summer Olympics?',
    correct_answer: 'Brazil',
    incorrect_answers: ['China', 'Ireland', 'Italy'],
  },
  {
    question: 'Which planet is the hottest?',
    correct_answer: 'Venus',
    incorrect_answers: ['Saturn', 'Mercury', 'Mars'],
  },
  {
    question: 'Who was the only U.S. President to resign?',
    correct_answer: 'Richard Nixon',
    incorrect_answers: ['Herbert Hoover', 'George W. Bush', 'Barack Obama'],
  },
  {
    question: 'What does the “D” in “D-Day” stand for?',
    correct_answer: 'Dunkirk',
    incorrect_answers: ['Dooms', 'Dark', 'Denmark'],
  },
  {
    question: 'In which city can you find the Liberty Bell?',
    correct_answer: 'Philadelphia',
    incorrect_answers: ['Washington, D.C.', 'Boston', 'Manhattan'],
  },
  {
    question: 'According to Forrest Gump, “life was like…”',
    correct_answer: 'A box of chocolates',
    incorrect_answers: ['A bag of lemons', 'A handful of roses', 'A lollipop'],
  },
  {
    question: 'What is the rarest blood type?',
    correct_answer: 'AB-Negative',
    incorrect_answers: ['O', 'B', 'A'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'What breed of dog was Marley in the film &quot;Marley &amp; Me&quot; (2008)?',
    correct_answer: 'Labrador Retriever',
    incorrect_answers: ['Golden Retriever', 'Dalmatian', 'Shiba Inu'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which of the following is NOT a quote from the 1942 film Casablanca? ',
    correct_answer: '&quot;Frankly, my dear, I don&#039;t give a damn.&quot;',
    incorrect_answers: [
      '&quot;Here&#039;s lookin&#039; at you, kid.&quot;',
      '&ldquo;Of all the gin joints, in all the towns, in all the world, she walks into mine&hellip;&rdquo;',
      '&quot;Round up the usual suspects.&quot;',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which of the following movies was not based on a novel by Stephen King? ',
    correct_answer: 'The Thing',
    incorrect_answers: ['Carrie', 'Misery', 'The Green Mile'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which animated movie was first to feature a celebrity as a voice actor?',
    correct_answer: 'Aladdin',
    incorrect_answers: [
      'Toy Story',
      'James and the Giant Peach',
      'The Hunchback of Notre Dame',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Velma Kelly and Roxie Hart are the protagonists of which Oscar winning movie?',
    correct_answer: 'Chicago',
    incorrect_answers: ['Dreamgirls', 'Cabaret', 'All That Jazz'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which actress danced the twist with John Travolta in &#039;Pulp Fiction&#039;?',
    correct_answer: 'Uma Thurman',
    incorrect_answers: ['Kathy Griffin', 'Pam Grier', 'Bridget Fonda'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Who voiced the character Draco in the 1996 movie &#039;DragonHeart&#039;?',
    correct_answer: 'Sean Connery',
    incorrect_answers: ['Dennis Quaid', 'Pete Postlethwaite', 'Brian Thompson'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In the 1984 movie &quot;The Terminator&quot;, what model number is the Terminator portrayed by Arnold Schwarzenegger?',
    correct_answer: 'T-800',
    incorrect_answers: ['I-950', 'T-888', 'T-1000'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which actor played the main character in the 1990 film &quot;Edward Scissorhands&quot;?',
    correct_answer: 'Johnny Depp',
    incorrect_answers: [' Clint Eastwood', 'Leonardo DiCaprio', 'Ben Stiller'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which movie contains the quote, &quot;Say hello to my little friend!&quot;?',
    correct_answer: 'Scarface',
    incorrect_answers: ['Reservoir Dogs', 'Heat', 'Goodfellas'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'What was Dorothy&#039;s surname in &#039;The Wizard Of Oz&#039;?',
    correct_answer: 'Gale',
    incorrect_answers: ['Perkins', 'Day', 'Parker'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What did Alfred Hitchcock use as blood in the film &quot;Psycho&quot;? ',
    correct_answer: 'Chocolate syrup',
    incorrect_answers: ['Ketchup', 'Red food coloring', 'Maple syrup'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What does TIE stand for in reference to the TIE Fighter in &quot;Star Wars&quot;?',
    correct_answer: 'Twin Ion Engine',
    incorrect_answers: [
      'Twin Iron Engine',
      'Twin Intercepter Engine',
      'Twin Inception Engine',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What did the first moving picture depict?',
    correct_answer: 'A galloping horse',
    incorrect_answers: [
      'A woman in a dress',
      'A man walking',
      'A crackling fire',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In the 1994 movie &quot;Speed&quot;, what is the minimum speed the bus must go to prevent to bomb from exploding?',
    correct_answer: '50 mph',
    incorrect_answers: ['60 mph', '40 mph', '70 mph'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Who plays Alice in the Resident Evil movies?',
    correct_answer: 'Milla Jovovich',
    incorrect_answers: ['Madison Derpe', 'Milla Johnson', 'Kim Demp'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Who plays the Nemesis in the Resident Evil movies?',
    correct_answer: 'Matthew Taylor',
    incorrect_answers: ['Jason Dip', 'Eric Mabius', 'Jimmy Matts'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'In 2012, which movie won every category in the 32nd &quot;Golden Raspberry Awards&quot;?',
    correct_answer: 'Jack and Jill',
    incorrect_answers: [
      'The Girl with the Dragon Tattoo',
      'Thor',
      'The King&#039;s Speech',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'In what Disney movie can you spot the character &quot;Pac-Man&quot; in if you look closely enough in some scenes?',
    correct_answer: 'Tron',
    incorrect_answers: ['Big Hero 6', 'Fantasia', 'Monsters, Inc.'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In the 2010 Nightmare on Elm Street reboot, who played Freddy Kruger?',
    correct_answer: 'Jackie Earle Haley',
    incorrect_answers: ['Tyler Mane', 'Derek Mears', 'Gunnar Hansen'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Which one of these films are shot entirely in one-take?',
    correct_answer: 'Russian Ark',
    incorrect_answers: [
      'Good Will Hunting',
      'Birdman',
      'Schindler&#039;s List',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which one of these actors is said to be cut from the film &#039;E.T. the Extra-Terrestrial&#039;?',
    correct_answer: 'Harrison Ford',
    incorrect_answers: [
      'Michael J. Fox',
      'Andy Kaufman',
      'Arnold Schwarzenegger',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which movie of film director Stanley Kubrick is known to be an adaptation of a Stephen King novel?',
    correct_answer: 'The Shining',
    incorrect_answers: [
      '2001: A Space Odyssey',
      ' Dr. Strangelove ',
      'Eyes Wide Shut',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What was another suggested name for, the 1985 film, Back to the Future?',
    correct_answer: 'Spaceman From Pluto',
    incorrect_answers: [
      'Hill Valley Time Travelers',
      'The Time Travelers',
      'The Lucky Man',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'In the movie &quot;Cast Away&quot; the main protagonist&#039;s best friend while on the island is named',
    correct_answer: 'Wilson',
    incorrect_answers: ['Carson', 'Jackson', 'Willy'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'In the 1964 film &quot;Zulu&quot;, what song does the British Army company sing before the final battle?',
    correct_answer: 'Men of Harlech',
    incorrect_answers: [
      'Scotland the Brave',
      'Colonel Bogey March',
      'The British Grenadiers',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Who played Sgt. Gordon Elias in &#039;Platoon&#039; (1986)?',
    correct_answer: 'Willem Dafoe',
    incorrect_answers: ['Charlie Sheen', 'Matt Damon', 'Johnny Depp'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Who in Pulp Fiction says &quot;No, they got the metric system there, they wouldn&#039;t know what the fuck a Quarter Pounder is.&quot;',
    correct_answer: 'Vincent Vega',
    incorrect_answers: ['Jules Winnfield', 'Jimmie Dimmick', 'Butch Coolidge'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Who voices the main character Blu in the 2011 animated film &quot;Rio&quot;?',
    correct_answer: 'Jesse Eisenberg',
    incorrect_answers: ['Michael Cera', 'Jonah Hill', 'Zach Galifianakis'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The 2002 film &quot;28 Days Later&quot; is mainly set in which European country?',
    correct_answer: 'United Kingdom',
    incorrect_answers: ['France', 'Italy', 'Germany'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In what year was the movie &quot;Police Academy&quot; released?',
    correct_answer: '1984',
    incorrect_answers: ['1986', '1985', '1983'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Darth Vader&#039;s famous reveal to Luke is iconic. But which of these is the right one?',
    correct_answer: '&quot;No. I am your father.&quot;',
    incorrect_answers: [
      '&quot;Luke, I am your father.&quot;',
      '&quot;You&#039;re wrong. I am your father.&quot;',
      '&quot;The truth is that I am your father.&quot;',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'This trope refers to minor characters that are killed off to show how a monster works.',
    correct_answer: 'Red Shirt',
    incorrect_answers: ['Minions', 'Expendables', 'Cannon Fodder'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which animated film did Steven Lisberger direct in 1980 before going on to direct Tron?',
    correct_answer: 'Animalympics',
    incorrect_answers: [
      'The Fox and the Hound',
      'The Black Cauldron',
      'The Great Mouse Detecive',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What was the name of the protagonist in the movie Commando (1985)?',
    correct_answer: 'John Matrix',
    incorrect_answers: ['Ben Richards', 'Douglas Quaid', 'Harry Tasker'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the correct spelling of the protagonist of the book in The NeverEnding Story (1984)?',
    correct_answer: 'Atreyu',
    incorrect_answers: ['Atrayu', 'Atraiyu', 'Atraeyu'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Who plays the character of Po in the Kung Fu Panda movies?',
    correct_answer: 'Jack Black',
    incorrect_answers: ['Mirana Jonnes', 'McConahey Ramses', 'Jim Petersson'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Who is the director of the 1991 film &quot;Silence of the Lambs&quot;?',
    correct_answer: 'Jonathan Demme',
    incorrect_answers: ['Stanley Kubrick', 'Frank Darabont', 'Michael Bay'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'In order to cut costs, what were most of the extras of Mad Max (1979) paid with?',
    correct_answer: 'Beer',
    incorrect_answers: ['Fast food', 'Food stamps', 'They weren&#039;t paid'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In &quot;Jurassic World&quot;, which company purchases InGen and creates Jurassic World?',
    correct_answer: 'Masrani Global Corporation ',
    incorrect_answers: [
      'Biology Synthetics Technologies',
      'International Genetics Incorporated',
      'International Genetic Technologies',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What is the species of the &quot;Predator&quot; in the 1987 movie &quot;Predator&quot;?',
    correct_answer: 'Yautja',
    incorrect_answers: ['Xenomorph', 'Praetorian', 'Phocrex'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In Mulan (1998), who is the leader of the Huns?',
    correct_answer: 'Shan Yu',
    incorrect_answers: ['Chien-Po', 'Li Shang', 'Fa Zhou'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the name of the queen&#039;s pet in A Bug&#039;s Life?',
    correct_answer: 'Aphie',
    incorrect_answers: ['Flik', 'Hopper', 'Dot'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question: 'In Big Hero 6, what were Baymax&#039;s motions modeled after?',
    correct_answer: 'Baby penguins',
    incorrect_answers: ['Baby monkeys', 'Baby ostriches', 'Baby bears'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In the Friday The 13th series, what is Jason&#039;s mother&#039;s first name?',
    correct_answer: 'Pamela',
    incorrect_answers: ['Mary', 'Christine', 'Angeline'],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which 90&#039;s comedy cult classic features cameos appearances from Meat Loaf, Alice Cooper and Chris Farley?',
    correct_answer: 'Wayne&#039;s World',
    incorrect_answers: [
      'Bill &amp; Ted&#039;s Excellent Adventure',
      'Dumb and Dumber',
      'Austin Powers: International Man of Mystery',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which 1994 film did Roger Ebert famously despise, saying &quot;I hated hated hated hated hated this movie&quot;.',
    correct_answer: 'North',
    incorrect_answers: [
      '3 Ninjas Kick Back',
      'The Santa Clause',
      'Richie Rich',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Who directed the Kill Bill movies?',
    correct_answer: 'Quentin Tarantino',
    incorrect_answers: [
      'Arnold Schwarzenegger',
      'David Lean',
      'Stanley Kubrick',
    ],
  },
  {
    category: 'Entertainment: Film',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which boxer was famous for striking the gong in the introduction to J. Arthur Rank films?',
    correct_answer: 'Bombardier Billy Wells',
    incorrect_answers: ['Freddie Mills', 'Terry Spinks', 'Don Cockell'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which internet company began life as an online bookstore called &#039;Cadabra&#039;?',
    correct_answer: 'Amazon',
    incorrect_answers: ['eBay', 'Overstock', 'Shopify'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'According to the International System of Units, how many bytes are in a kilobyte of RAM?',
    correct_answer: '1000',
    incorrect_answers: ['512', '1024', '500'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What was the name of the security vulnerability found in Bash in 2014?',
    correct_answer: 'Shellshock',
    incorrect_answers: ['Heartbleed', 'Bashbug', 'Stagefright'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Whistler was the codename of this Microsoft Operating System.',
    correct_answer: 'Windows XP',
    incorrect_answers: ['Windows 2000', 'Windows 7', 'Windows 95'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...',
    correct_answer: 'Year',
    incorrect_answers: ['Four Years', 'Two Years', 'Eight Years'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What does AD stand for in relation to Windows Operating Systems? ',
    correct_answer: 'Active Directory',
    incorrect_answers: [
      'Alternative Drive',
      'Automated Database',
      'Active Department',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'When was the programming language &quot;C#&quot; released?',
    correct_answer: '2000',
    incorrect_answers: ['1998', '1999', '2001'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The programming language &#039;Swift&#039; was created to replace what other programming language?',
    correct_answer: 'Objective-C',
    incorrect_answers: ['C#', 'Ruby', 'C++'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'HTML is what type of language?',
    correct_answer: 'Markup Language',
    incorrect_answers: [
      'Macro Language',
      'Programming Language',
      'Scripting Language',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What amount of bits commonly equals one byte?',
    correct_answer: '8',
    incorrect_answers: ['1', '2', '64'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which computer hardware device provides an interface for all other connected devices to communicate?',
    correct_answer: 'Motherboard',
    incorrect_answers: [
      'Central Processing Unit',
      'Hard Disk Drive',
      'Random Access Memory',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'On which computer hardware device is the BIOS chip located?',
    correct_answer: 'Motherboard',
    incorrect_answers: [
      'Hard Disk Drive',
      'Central Processing Unit',
      'Graphics Processing Unit',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which of the following languages is used as a scripting language in the Unity 3D game engine?',
    correct_answer: 'C#',
    incorrect_answers: ['Java', 'C++', 'Objective-C'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'All of the following programs are classified as raster graphics editors EXCEPT:',
    correct_answer: 'Inkscape',
    incorrect_answers: ['Paint.NET', 'GIMP', 'Adobe Photoshop'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:',
    correct_answer: 'HD Graphics 500',
    incorrect_answers: [
      'HD Graphics 700 ',
      'HD Graphics 600',
      'HD Graphics 7000',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Nvidia&#039;s headquarters are based in which Silicon Valley city?',
    correct_answer: 'Santa Clara',
    incorrect_answers: ['Palo Alto', 'Cupertino', 'Mountain View'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'What is the most preferred image format used for logos in the Wikimedia database?',
    correct_answer: '.svg',
    incorrect_answers: ['.png', '.jpeg', '.gif'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What was the first commerically available computer processor?',
    correct_answer: 'Intel 4004',
    incorrect_answers: ['Intel 486SX', 'TMS 1000', 'AMD AM386'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'In web design, what does CSS stand for?',
    correct_answer: 'Cascading Style Sheet',
    incorrect_answers: [
      'Counter Strike: Source',
      'Corrective Style Sheet',
      'Computer Style Sheet',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which of these is the name for the failed key escrow device introduced by the National Security Agency in 1993?',
    correct_answer: 'Clipper Chip',
    incorrect_answers: ['Enigma Machine', 'Skipjack', 'Nautilus'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'What is the code name for the mobile operating system Android 7.0?',
    correct_answer: 'Nougat',
    incorrect_answers: ['Ice Cream Sandwich', 'Jelly Bean', 'Marshmallow'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What does the acronym CDN stand for in terms of networking?',
    correct_answer: 'Content Delivery Network',
    incorrect_answers: [
      'Content Distribution Network',
      'Computational Data Network',
      'Compressed Data Network',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How many kilobytes in one gigabyte?',
    correct_answer: '1000000',
    incorrect_answers: ['1024', '1000', '1048576'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the name of the default theme that is installed with Windows XP?',
    correct_answer: 'Luna',
    incorrect_answers: ['Neptune', 'Whistler', 'Bliss'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?',
    correct_answer: 'print(&quot;Hello World&quot;)',
    incorrect_answers: [
      'console.log(&quot;Hello World&quot;)',
      'echo &quot;Hello World&quot;',
      'printf(&quot;Hello World&quot;)',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?',
    correct_answer: '&lt;marquee&gt;&lt;/marquee&gt;',
    incorrect_answers: [
      '&lt;scroll&gt;&lt;/scroll&gt;',
      '&lt;move&gt;&lt;/move&gt;',
      '&lt;slide&gt;&lt;/slide&gt;',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which computer language would you associate Django framework with?',
    correct_answer: 'Python',
    incorrect_answers: ['C#', 'C++', 'Java'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In computing terms, typically what does CLI stand for?',
    correct_answer: 'Command Line Interface',
    incorrect_answers: [
      'Common Language Input',
      'Control Line Interface',
      'Common Language Interface',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'How fast is USB 3.1 Gen 2 theoretically?',
    correct_answer: '10 Gb/s',
    incorrect_answers: ['5 Gb/s', '8 Gb/s', '1 Gb/s'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Which operating system was released first?',
    correct_answer: 'Mac OS',
    incorrect_answers: ['Windows', 'Linux', 'OS/2'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The numbering system with a radix of 16 is more commonly referred to as ',
    correct_answer: 'Hexidecimal',
    incorrect_answers: ['Binary', 'Duodecimal', 'Octal'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is known as &quot;the brain&quot; of the Computer?',
    correct_answer: 'Central Processing Unit',
    incorrect_answers: ['Motherboard', 'Graphics Processing Unit', 'Keyboard'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which of the following is the oldest of these computers by release date?',
    correct_answer: 'TRS-80',
    incorrect_answers: ['Commodore 64', 'ZX Spectrum', 'Apple 3'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What is the name of the process that sends one qubit of information using two bits of classical information?',
    correct_answer: 'Quantum Teleportation',
    incorrect_answers: [
      'Super Dense Coding',
      'Quantum Entanglement',
      'Quantum Programming',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What internet protocol was documented in RFC 1459?',
    correct_answer: 'IRC',
    incorrect_answers: ['HTTP', 'HTTPS', 'FTP'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the main CPU is the Sega Mega Drive / Sega Genesis?',
    correct_answer: 'Motorola 68000',
    incorrect_answers: ['Zilog Z80', 'Yamaha YM2612', 'Intel 8088'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What does the International System of Quantities refer 1024 bytes as?',
    correct_answer: 'Kibibyte',
    incorrect_answers: ['Kylobyte', 'Kilobyte', 'Kelobyte'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which RAID array type is associated with data mirroring?',
    correct_answer: 'RAID 1',
    incorrect_answers: ['RAID 0', 'RAID 10', 'RAID 5'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Laserjet and inkjet printers are both examples of what type of printer?',
    correct_answer: 'Non-impact printer',
    incorrect_answers: [
      'Impact printer',
      'Daisywheel printer',
      'Dot matrix printer',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What was the first company to use the term &quot;Golden Master&quot;?',
    correct_answer: 'Apple',
    incorrect_answers: ['IBM', 'Microsoft', 'Google'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How many values can a single byte represent?',
    correct_answer: '256',
    incorrect_answers: ['8', '1', '1024'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Dutch computer scientist Mark Overmars is known for creating which game development engine?',
    correct_answer: 'Game Maker',
    incorrect_answers: ['Stencyl', 'Construct', 'Torque 2D'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Approximately how many Apple I personal computers were created?',
    correct_answer: '200',
    incorrect_answers: ['100', '500', '1000'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'Which programming language shares its name with an island in Indonesia?',
    correct_answer: 'Java',
    incorrect_answers: ['Python', 'C', 'Jakarta'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In programming, what do you call functions with the same name but different implementations?',
    correct_answer: 'Overloading',
    incorrect_answers: ['Overriding', 'Abstracting', 'Inheriting'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'In computing, what does MIDI stand for?',
    correct_answer: 'Musical Instrument Digital Interface',
    incorrect_answers: [
      'Musical Interface of Digital Instruments',
      'Modular Interface of Digital Instruments',
      'Musical Instrument Data Interface',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'easy',
    question: 'In computing, what does LAN stand for?',
    correct_answer: 'Local Area Network',
    incorrect_answers: [
      'Long Antenna Node',
      'Light Access Node',
      'Land Address Navigation',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'medium',
    question: 'How many bytes are in a single Kibibyte?',
    correct_answer: '1024',
    incorrect_answers: ['2400', '1000', '1240'],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:',
    correct_answer: 'A&#039; + B&#039;',
    incorrect_answers: [
      'A&#039;B + B&#039;A',
      'A&#039;B&#039;',
      'AB&#039; + AB',
    ],
  },
  {
    category: 'Science: Computers',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What major programming language does Unreal Engine 4 use?',
    correct_answer: 'C++',
    incorrect_answers: ['Assembly', 'C#', 'ECMAScript'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What was the name of the Ethiopian Wolf before they knew it was related to wolves?',
    correct_answer: 'Simien Jackel',
    incorrect_answers: ['Ethiopian Coyote', 'Amharic Fox', 'Canis Simiensis'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What does &quot;hippopotamus&quot; mean and in what langauge?',
    correct_answer: 'River Horse (Greek)',
    incorrect_answers: [
      'River Horse (Latin)',
      'Fat Pig (Greek)',
      'Fat Pig (Latin)',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'A carnivorous animal eats flesh, what does a nucivorous animal eat?',
    correct_answer: 'Nuts',
    incorrect_answers: ['Nothing', 'Fruit', 'Seaweed'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What type of animal is a natterjack?',
    correct_answer: 'Toad',
    incorrect_answers: ['Bird', 'Fish', 'Insect'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the fastest  land animal?',
    correct_answer: 'Cheetah',
    incorrect_answers: [
      'Lion',
      'Thomson&rsquo;s Gazelle',
      'Pronghorn Antelope',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the scientific name for modern day humans?',
    correct_answer: 'Homo Sapiens',
    incorrect_answers: [
      'Homo Ergaster',
      'Homo Erectus',
      'Homo Neanderthalensis',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The Kākāpō is a large, flightless, nocturnal parrot native to which country?',
    correct_answer: 'New Zealand',
    incorrect_answers: ['South Africa', 'Australia', 'Madagascar'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which species of Brown Bear is not extinct?',
    correct_answer: 'Syrian Brown Bear',
    incorrect_answers: [
      'California Grizzly Bear',
      'Atlas Bear',
      'Mexican Grizzly Bear',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What color/colour is a polar bear&#039;s skin?',
    correct_answer: 'Black',
    incorrect_answers: ['White', 'Pink', 'Green'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Hippocampus is the Latin name for which marine creature?',
    correct_answer: 'Seahorse',
    incorrect_answers: ['Dolphin', 'Whale', 'Octopus'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Cashmere is the wool from which kind of animal?',
    correct_answer: 'Goat',
    incorrect_answers: ['Sheep', 'Camel', 'Llama'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the scientific name for the &quot;Polar Bear&quot;?',
    correct_answer: 'Ursus Maritimus',
    incorrect_answers: ['Polar Bear', 'Ursus Spelaeus', 'Ursus Arctos'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What are rhino&#039;s horn made of?',
    correct_answer: 'Keratin',
    incorrect_answers: ['Bone', 'Ivory', 'Skin'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How many legs do butterflies have?',
    correct_answer: '6',
    incorrect_answers: ['2', '4', '0'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What scientific suborder does the family Hyaenidae belong to?',
    correct_answer: 'Feliformia',
    incorrect_answers: ['Haplorhini', 'Caniformia', 'Ciconiiformes'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'How many known living species of hyenas are there?',
    correct_answer: '4',
    incorrect_answers: ['8', '2', '6'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What scientific family does the Aardwolf belong to?',
    correct_answer: 'Hyaenidae',
    incorrect_answers: ['Canidae', 'Felidae', 'Eupleridae'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What do you call a baby bat?',
    correct_answer: 'Pup',
    incorrect_answers: ['Cub', 'Chick', 'Kid'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the scientific name of the cheetah?',
    correct_answer: 'Acinonyx jubatus',
    incorrect_answers: ['Panthera onca', 'Lynx rufus', 'Felis catus'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the scientific name of the Budgerigar?',
    correct_answer: 'Melopsittacus undulatus',
    incorrect_answers: [
      'Nymphicus hollandicus',
      'Pyrrhura molinae',
      'Ara macao',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'Which animal was part of an Russian domestication experiment in 1959?',
    correct_answer: 'Foxes',
    incorrect_answers: ['Pigeons', 'Bears', 'Alligators'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'The now extinct species &quot;Thylacine&quot; was native to where?',
    correct_answer: 'Tasmania, Australia',
    incorrect_answers: [
      'Baluchistan, Pakistan',
      'Wallachia, Romania',
      'Oregon, United States',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the Gray Wolf&#039;s scientific name?',
    correct_answer: 'Canis Lupus',
    incorrect_answers: ['Canis Aureus', 'Canis Latrans', 'Canis Lupus Lycaon'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which of these animals is NOT a lizard?',
    correct_answer: 'Tuatara',
    incorrect_answers: ['Komodo Dragon', 'Gila Monster', 'Green Iguana'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is Grumpy Cat&#039;s real name?',
    correct_answer: 'Tardar Sauce',
    incorrect_answers: ['Sauce', 'Minnie', 'Broccoli'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What type of creature is a Bonobo?',
    correct_answer: 'Ape',
    incorrect_answers: ['Lion', 'Parrot', 'Wildcat'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Which of these species is not extinct?',
    correct_answer: 'Komodo dragon',
    incorrect_answers: [
      'Japanese sea lion',
      'Tasmanian tiger',
      'Saudi gazelle',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Which class of animals are newts members of?',
    correct_answer: 'Amphibian',
    incorrect_answers: ['Fish', 'Reptiles', 'Mammals'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Unlike on most salamanders, this part of a newt is flat?',
    correct_answer: 'Tail',
    incorrect_answers: ['Head', 'Teeth', 'Feet'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the name of the family that the domestic cat is a member of?',
    correct_answer: 'Felidae',
    incorrect_answers: ['Felinae', 'Felis', 'Cat'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What dog bread is one of the oldest breeds of dog and has flourished since before 400 BCE.',
    correct_answer: 'Pugs',
    incorrect_answers: ['Bulldogs', 'Boxers', 'Chihuahua'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What is the name of the copper-rich protein that creates the blue blood in the Antarctic octopus?',
    correct_answer: 'Hemocyanin',
    incorrect_answers: ['Cytochrome', 'Iron', 'Methionine'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which species is a &quot;mountain chicken&quot;?',
    correct_answer: 'Frog',
    incorrect_answers: ['Chicken', 'Horse', 'Fly'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the fastest animal?',
    correct_answer: 'Peregrine Falcon',
    incorrect_answers: ['Golden Eagle', 'Cheetah', 'Horsefly'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'The dish Fugu, is made from what family of fish?',
    correct_answer: 'Pufferfish',
    incorrect_answers: ['Bass', 'Salmon', 'Mackerel'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the collective noun for a group of crows?',
    correct_answer: 'Murder',
    incorrect_answers: ['Pack', 'Gaggle', 'Herd'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which of the following is another name for the &quot;Poecilotheria Metallica Tarantula&quot;?',
    correct_answer: 'Gooty',
    incorrect_answers: ['Hopper', 'Silver Stripe', 'Woebegone'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the scientific name of the Common Chimpanzee?',
    correct_answer: 'Pan troglodytes',
    incorrect_answers: ['Gorilla gorilla', 'Pan paniscus', 'Panthera leo'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'By definition, where does an abyssopelagic animal live?',
    correct_answer: 'At the bottom of the ocean',
    incorrect_answers: [
      'In the desert',
      'On top of a mountain',
      'Inside a tree',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which of these is a colony of polyps and not a jellyfish?',
    correct_answer: 'Portuguese Man-of-War',
    incorrect_answers: ['Sea Wasp', 'Irukandji', 'Sea Nettle'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What colour is the female blackbird?',
    correct_answer: 'Brown',
    incorrect_answers: ['Black', 'White', 'Yellow'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the common term for bovine spongiform encephalopathy (BSE)?',
    correct_answer: 'Mad Cow disease',
    incorrect_answers: [
      'Weil&#039;s disease',
      'Milk fever',
      'Foot-and-mouth disease',
    ],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How many teeth does an adult rabbit have?',
    correct_answer: '28',
    incorrect_answers: ['30', '26', '24'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the name for a male bee that comes from an unfertilized egg?',
    correct_answer: 'Drone',
    incorrect_answers: ['Soldier', 'Worker', 'Male'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the name of a rabbit&#039;s abode?',
    correct_answer: 'Burrow',
    incorrect_answers: ['Nest', 'Den', 'Dray'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the collective noun for bears?',
    correct_answer: 'Sloth',
    incorrect_answers: ['Drove', 'Tribe', 'Husk'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the collective noun for rats?',
    correct_answer: 'Mischief',
    incorrect_answers: ['Pack', 'Race', 'Drift'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the collective noun for vultures?',
    correct_answer: 'Wake',
    incorrect_answers: ['Ambush', 'Building', 'Gaze'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What bird is born with claws on its wing digits?',
    correct_answer: 'Hoatzin',
    incorrect_answers: ['Cormorant', 'Cassowary', 'Secretary bird'],
  },
  {
    category: 'Animals',
    type: 'multiple',
    difficulty: 'medium',
    question:
      '&quot;Decapods&quot; are an order of ten-footed crustaceans.  Which of these are NOT decapods?',
    correct_answer: 'Krill',
    incorrect_answers: ['Lobsters', 'Shrimp', 'Crabs'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'In a complete graph G, which has 12 vertices, how many edges are there?',
    correct_answer: '66',
    incorrect_answers: ['67', '34', '11'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How is the number 9 represented as a binary number?',
    correct_answer: '1001',
    incorrect_answers: ['1000', '1110', '1010'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the derivative of Acceleration with respect to time?',
    correct_answer: 'Jerk',
    incorrect_answers: ['Shift', 'Bump', 'Slide'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the approximate value of mathematical constant e?',
    correct_answer: '2.72',
    incorrect_answers: ['3.14', '1.62', '1.41'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question: 'How many zeros are there in a googol?',
    correct_answer: '100',
    incorrect_answers: ['10', '1,000', '1,000,000'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the area of a circle with a diameter of 20 inches if &pi;= 3.1415?',
    correct_answer: '314.15 Inches',
    incorrect_answers: ['380.1215 Inches', '3141.5 Inches', '1256.6 Inches'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question: 'In Roman Numerals, what does XL equate to?',
    correct_answer: '40',
    incorrect_answers: ['60', '15', '90'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the Roman numeral for 500?',
    correct_answer: 'D',
    incorrect_answers: ['L', 'C', 'X'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What&#039;s the square root of 49?',
    correct_answer: '7',
    incorrect_answers: ['4', '12', '9'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question: 'How many zeptometres are inside one femtometre?',
    correct_answer: '1,000,000',
    incorrect_answers: ['10', '1,000,000,000', '1000'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the first Mersenne prime exponent over 1000?',
    correct_answer: '1279',
    incorrect_answers: ['2203', '1009', '1069'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'medium',
    question:
      'What is the alphanumeric representation of the imaginary number?',
    correct_answer: 'i',
    incorrect_answers: ['e', 'n', 'x'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question: 'The decimal number 31 in hexadecimal would be what?',
    correct_answer: '1F',
    incorrect_answers: ['3D', '2E', '1B'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the 100th digit of Pi?',
    correct_answer: '9',
    incorrect_answers: ['4', '7', '2'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the symbol for Displacement?',
    correct_answer: '&Delta;r',
    incorrect_answers: ['dr', 'Dp', 'r'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question:
      'The metric prefix &quot;atto-&quot; makes a measurement how much smaller than the base unit?',
    correct_answer: 'One Quintillionth',
    incorrect_answers: [
      'One Billionth',
      'One Quadrillionth',
      'One Septillionth',
    ],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'easy',
    question: 'How many sides does a heptagon have?',
    correct_answer: '7',
    incorrect_answers: ['8', '6', '5'],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'What is the plane curve proposed by Descartes to challenge Fermat&#039;s extremum-finding techniques called?',
    correct_answer: 'Folium of Descartes',
    incorrect_answers: [
      'Elliptic Paraboloid of Descartes',
      'Cartesian Coordinates',
      'Descarte&#039;s Helicoid',
    ],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'The French mathematician &Eacute;variste Galois is primarily known for his work in which?',
    correct_answer: 'Galois Theory',
    incorrect_answers: [
      'Galois&#039; Continued Fractions',
      'Galois&#039; Method for PDE&#039;s ',
      'Abelian Integration',
    ],
  },
  {
    category: 'Science: Mathematics',
    type: 'multiple',
    difficulty: 'hard',
    question:
      'Which of these numbers is closest to the total number of possible states for an army standard Enigma Machine?',
    correct_answer: '1.58 x 10^20',
    incorrect_answers: ['1.58 x 10^22', '1.58 x  10^18', '1.58 x 10^24'],
  },
];

export default questionsJson;
